### ISSUE TITLE
Add integration with a URL shortener (goo.gl) for demo pages

### ISSUE THREAD

**Issue by tocttou** [batra-mlp-lab/CloudCVfy-Frontend#6]

**Comment by DESHRAJ** [comment]
Shouldn't we have our own shortener link ? That will increase our visibility. It could be something like `cvfy.cloudcv.org/abcde`

@dexter1691 @tocttou

**Comment by tocttou** [comment]
Looks good to me. Can be integrated in the app itself.

**Comment by tocttou** [comment]
87517a1679014d110d90d0c79b69b82e3a4de17d adds this functionality.
