### ISSUE TITLE
Remove the labels that are empty

### ISSUE THREAD

**Issue by DESHRAJ** [batra-mlp-lab/CloudCVfy-Frontend#9]
While adding the fields, there should be option to remove the label if accidently pressed the button 'Add Field'. 
See the Screenshot attached. 
![screenshot from 2016-06-23 09 25 00](https://cloud.githubusercontent.com/assets/2945708/16304668/6ea17288-3924-11e6-8918-561a54925759.png)

**Comment by tocttou** [comment]
bead97a  fixes this
